### ISSUE TITLE
Duplicate library

### ISSUE THREAD

**Issue by elupus** [yozik04/nibe#8]
Not a real issue. I just found your library while working on my own (https://github.com/elupus/nibeudp). Im thinking of writing a home assistant integration for nibe, (was thinking native instead of mqtt) to at some point replace my nibe uplink one.

Let me know if i can help out in some way. Im elupus on discord, feel free to drop me a pm.

**Comment by yozik04** [comment]
@elupus I've seen your [hass_nibe](https://github.com/elupus/hass_nibe) some years ago and that time I asked if you want to add UDP or NibeGW support there. We did not agree on cooperation that time. So now it came out that we are doing the same thing =)
My library is quite baked already with most of sensors already available and most bugs ironed out.
I had a plan to add nibe uplink to my library in future as well. It is designed the way when it should be very easy to add new connection methods.
HomeAssistant integration would be great. I personally picked MQTT because I did migration from Openhab. It was much easier to do it via MQTT. Also HomeAssistant maintainers are very overloaded. I am waiting for my PRs on an other integration for a month already.
@elupus I would be more than happy if you can lead HomeAssistant integration development. I can help you with that.
